### PR TITLE
use items instead of iteritems

### PR DESCRIPTION
**Pull request by mamico**
This seems to make the package usable even with newer versions of Zope.

Thx.

### CODE REVIEW

**Comment by rpatterson** [comment]
Looks good to me. Using `iteritems()` was probably a premature optimization at the time it was written anyways. I merged this blindly as I've not used this for many years and have no easily available test-bed. If you or anyone else want's to maintain this project, @mamico, just LMK.

**Comment by mamico** [comment]
> Looks good to me. Using `iteritems()` was probably a premature optimization at the time it was written anyways. I merged this blindly as I've not used this for many years and have no easily available test-bed. If you or anyone else want's to maintain this project, @mamico, just LMK.

@rpatterson thank you. If you move the repository to https://github.com/collective and give me permission to release to pypi (my pypi user is mauro), I can help you. For instance I can do a new release and add the current tests to the github actions. I use the product from time to time, for example when I need to debug some old db.

**Comment by rpatterson** [comment]
> If you move the repository to https://github.com/collective and give me permission to release to pypi (my pypi user is mauro), I can help you.

Thanks for the instructions. I've transferred the project. I already have [@collective on PyPI](https://pypi.org/user/collective/) as a "Collaborator" with the `Owner` "Role". Do I also need to add you, @mamico? Once we've got this project successfully transfered, I'll do the same with any remaining projects under my personal user that are related to Plone or Zope.

> For instance I can do a new release and add the current tests to the github actions.

Much more than I could ask for, thanks in advance!

> I use the product from time to time, for example when I need to debug some old db.

So awesome to hear. I never got the sense anyone but me ever used it. The name I gave it didn't help, I remember the stifled laughs when I tried to demo it.  ;-)

**Comment by rpatterson** [comment]
Just one more reminder, @mamico. Just LMK if you want to finish taking over maintenance!

**Comment by mamico** [comment]
> Just one more reminder, @mamico. Just LMK if you want to finish taking over maintenance!

@rpatterson August is mostly the month of vacations, in Italy ;)

**Comment by rpatterson** [comment]
> August is mostly the month of vacations, in Italy ;)

Sorry, I didn't mean that as pressure, I was just sending one more note before taking it off my TODO list. Please don't let me interrupt your vacation!

**Pull request merged**
